FROM golang:1.22.3-alpine3.19 AS builder
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /out/paper-street-server ./cmd/paper-street-server

FROM alpine:3.19.1
RUN apk add --no-cache ca-certificates
WORKDIR /app
COPY --from=builder /out/paper-street-server ./paper-street-server
COPY --from=builder /src/frontend ./frontend
EXPOSE 8000
CMD ["./paper-street-server"]
